### ISSUE TITLE
Ports - Was anderes als 8000/8001?

### ISSUE THREAD

**Issue by chrisinabztf** [bylexus/docsify-starter#1]
Die Ports 8000 und 8001 werden noch relativ häufig von anderen Diensten verwendet - so kann es bei der parallelen Entwicklung und Dokumentation zu unnötigen Konflikten kommen. 

Anfrage: Könnte man die Ports auf 10000 und 10001 (oder so) festlegen?

**Comment by chrisinabztf** [comment]
Vorschlag (zur Diskussion) für weitere Plugins und prism-Sprachen - index.html im Anhang.

[index.zip](https://github.com/bylexus/docsify-starter/files/4585193/index.zip)

**Comment by bylexus** [comment]
Ja, das ist machbar. Ich schaue mal, ob da sogar was mit env vars machbar ist, sodass man dies "von aussen" bei docker-compose up wählen kann

**Comment by bylexus** [comment]
- Port 10000: Web
- Port 10001: PlantUML
- Port 35729: Live Reload port
